### ISSUE TITLE
Wrong patterns

### ISSUE THREAD

**Issue by kventinel** [MikeMirzayanov/testlib#103]
Validator fail on readLine with line "abc abc" and pattern "[a-z ]+".

**Comment by fer22f** [comment]
Spaces are removed here for some reason in all patterns:

https://github.com/MikeMirzayanov/testlib/blob/1277b269ec417dc01a786a6775a10b9189a0fadc/testlib.h#L1327-L1331

**Solution:** Escape spaces (`__pattern_isCommandChar` returns `false`) like so:
```cpp
inf.readLine("[a-z\\ ]+", "s");
```
