### ISSUE TITLE
quitf(_pc(score), ...) not work

### ISSUE THREAD

**Issue by sshwy** [MikeMirzayanov/testlib#115]
I'm trying to run the following checker:

```cpp
#include "testlib.h"
#include <map>
#include <vector>
using namespace std;

int n;
string s;

int main(int argc, char* argv[]) {
    registerTestlibCmd(argc, argv);

    quitf(_pc(13), "result=%d", 100);
    
    return 0;
}
```

However I get `wrong output format Extra information in the output file` instead of partial score information. What should I do ?

**Comment by MikeMirzayanov** [comment]
use `quitp`; `quitf+_pc` is just for compatibility with old pascal-testlib
