### ISSUE TITLE
rnd.partition() for size = 0 and sum = 0

### ISSUE THREAD

**Issue by shishyando** [MikeMirzayanov/testlib#125]
https://github.com/MikeMirzayanov/testlib/blob/f5b55f138709e97916f51bdb7a23baed941b5751/testlib.h#L1058
`rnd.partition()` does not work correctly only when `size = 0` and `sum = 0` (and any `min_part`)
It calls `rnd.distinct(-1, 0, -1)`  which raises `__testlib_fail("random_t::distinct expected from <= to")`
In this case the result of `rnd.partition()` should be an empty vector, not a testlib fail. I think that pull request #124 may pull this bugfix also.

If you are wondering whether it works in other cases:

- If `size < 0` then a fail is raised
- If `size = 0` and `sum != 0` a fail is raised
- If `size = 0` and `sum = 0` there is a bug I mentioned
- If `size = 1` `rnd.distinct(0,...)` is called and it returns an empty vector
- If `size > 1` then `distinct(size - 1, T(1), T(sum + size - 1))` works correctly because of that:

1. `size - 1 > 0`
2. `sum - min_part * size >= 0` [(L1051-L1055)](https://github.com/MikeMirzayanov/testlib/blob/f5b55f138709e97916f51bdb7a23baed941b5751/testlib.h#L1051)
3. Then `sum - min_part * size + size - 1 > 0` thus it's not less than 1 and all parameters for `rnd.distinct()` are correct.

**Comment by MikeMirzayanov** [comment]
Please, check the issue now and write your verdict for the current state of the source code.

**Comment by shishyando** [comment]
The issue is still there...
https://github.com/MikeMirzayanov/testlib/blob/1b424474b044adae04d63528240656fc686435f2/testlib.h#L1049-L1056

Here should be added an if case:
`if (size == 0 && sum == 0)
    return std::vector<T>()`

**Comment by MikeMirzayanov** [comment]
Like this? https://github.com/MikeMirzayanov/testlib/commit/750b0308df70ca899c351e15246419f71fc6a9b5

**Comment by shishyando** [comment]
Yes, this should do it
