### ISSUE TITLE
Fatal error in reading integers

### ISSUE THREAD

**Issue by yhx-12243** [MikeMirzayanov/testlib#127]
The function `stringToLongLong` in function `readInt` converts `_tmpReadToken` to `const char *`, but `_tmpReadToken` may contain null character (`\0`) so it will accept invalid data.

> https://github.com/MikeMirzayanov/testlib/blob/f5b55f138709e97916f51bdb7a23baed941b5751/testlib.h#L3333-L3344

example code:
```cpp
#include "testlib.h"

int main(int argc, char *argv[]) {
	registerValidation(argc, argv);
	inf.readInt(), inf.readEoln();
	inf.readEof();
	return 0;
}
```

example input:
<code>
0<b>\0</b>0
</code>

where **\0** represents null character.

**Comment by MikeMirzayanov** [comment]
Fixed. Please, review the code

**Comment by MikeMirzayanov** [comment]
Fixed now
