### ISSUE TITLE
Submition time guarantee

### ISSUE THREAD

**Issue by MatesV13** [MikeMirzayanov/testlib#131]
Sometimes it is crutial to know when some code was submitted (or evaluated or...), to know if you should do something.

My checker uses testlib, and trys to get time of server with time(0), but for multiple runs i get same time, and that time is not even close to current time (about an hour and a half appart), so I'm guessing that there is some other feature in servers that assures that random codes with seed that is time get same output. 

That is well and ok for participants, put for me as a setter, i need to know what time it is in my checker/validator/generator/interactor... Maybe put some way in testlib to fetch current time?

**Comment by MikeMirzayanov** [comment]
Testlib is not responsible for time routine
