### ISSUE TITLE
Sometimes wnext(int n, int type) = n (which violates the guaranteed behavior of wnext)

### ISSUE THREAD

**Issue by dario2994** [MikeMirzayanov/testlib#133]
The function `wnext(int n, int type)` is guaranteed to return an integer in the range `[0, n-1)`.
This is false, as the following code shows (compiled with `g++ -O2 gen.cpp -o gen`):

```
#include "testlib.h"
#include <cassert>
 
int main() {
    for (int i = 0; i < 1e8; i++) assert(1 != rnd.wnext(1, (int)1e9));
}
```
The error is caused by the assumption that (lines 788--793 in testlib.h):
```
p = std::pow(next() + 0.0, 1.0 / (type + 1));
return int(n * p);
```
returns a value strictly smaller than `n`.

I would suggest to simply fix it by replacing `return int(n*p);` with
```
int res = n*p;
if (res == n) res--;
return res;
```

**Comment by yhx-12243** [comment]
#76

**Comment by MikeMirzayanov** [comment]
Review the code around wnext(double), probably, use nextafter

**Comment by MikeMirzayanov** [comment]
~~~~~
    double wnext(double from, double to, int type) {
        if (from > to)
            __testlib_fail("random_t::wnext(double from, double to, int type): from can't not exceed to");
        return wnext(to - from, type) + from;
    }
~~~~~

Probably, from >= to

**Comment by MikeMirzayanov** [comment]
Fixed now
