### ISSUE TITLE
testlib в ejudge портит info-файлы, передаваемые чекеру в argv[4]

### ISSUE THREAD

**Issue by dkirienko** [MikeMirzayanov/testlib#170]
Если запускать testlib в ejudge с поддержкой info-файлов, то имя этого файла передается чекеру в argv[4], например:

/home/judges/043507/problems/A/check /home/judges/043507/problems/A/tests/01 a.out /home/judges/043507/problems/A/tests/01.a /home/judges/043507/problems/A/tests/01.inf

В этом случае testlib выводит комментарий в argv[4], тем самым перезаписывая info-файлы.

Предлагается сделать в функции registerTestlibCmd по аналогии с registerInteraction
#ifndef EJUDGE
в соответствующем месте.

**Comment by MikeMirzayanov** [comment]
Сделал такое

https://github.com/MikeMirzayanov/testlib/commit/b940a91c9eaf04372aa8e45b8cf35121d45d0946

Но сам воспроизвести или что-то проверить не могу.

Хорошо бы кто-то с ejudge бы окнул.

**Comment by dkirienko** [comment]
Я думаю, что до зимы у меня точно повода смотреть не возникнет, вот в зимнюю ЛКШ если захочу повторить тот контест, который был зимой прошедшей, то тогда может быть покопаюсь.
