### ISSUE TITLE
How to run the solution twice in a judge turn?

### ISSUE THREAD

**Issue by OY9R** [MikeMirzayanov/testlib#175]
I want achieve a special-judge of this problem:
>input two strings $o$ and $s$
>    if $o$ is `compression` , output $s$ after compression.
>    if $o$ is `decompression` , output $s$ after decompression.

In ord to judge the solution, I need run the solution twice:
1. input `compression` and randen string $s$ to get the string after compression.
2. restart the solution, input `decompression` and the compressed string to get the decompressed string $s'$.
3. compare strings $s$ and $s'$.

But I don't know how to run the solution twice in a judge turn. I need some help.

**Comment by MikeMirzayanov** [comment]
This question is not about Testlib. I suggest you to ask on Codeforces.
