### ISSUE TITLE
readLong for unsigned long long

### ISSUE THREAD

**Issue by GoogleCodeExporter** [MikeMirzayanov/testlib#37]
```
Hi,

I wrote a patch for testlib.h release 0.9.5 as little example.
```

Original issue reported on code.google.com by `nap0r...@gmail.com` on 6 Apr 2014 at 4:56

Attachments:
* [readLong_for_ull.patch](https://storage.googleapis.com/google-code-attachments/testlib/issue-37/comment-0/readLong_for_ull.patch)

**Comment by MikeMirzayanov** [comment]
Done.
