### ISSUE TITLE
std::max конфликтует с minwindef.h

### ISSUE THREAD

**Issue by vfolunin** [MikeMirzayanov/testlib#46]
В методе `ValidatorBoundsHit::merge` имеются два обращения к `std::max` (строки 1883, 1884).
При подключении windows.h подключаются windef.h и minwindef.h, в котором `max` определено как макрос, что приводит к ошибке компиляции (error C2589: (: недопустимая лексема справа от "::").
Вызовы `std::max` следует заменить на `max`, `(std::max)` или `__testlib_max`.

**Comment by stgatilov** [comment]
Можно просто залить исправление отсюда: https://github.com/MikeMirzayanov/testlib/pull/50

**Comment by MikeMirzayanov** [comment]
Принял исправление, спасибо.
