### ISSUE TITLE
readDouble() does not read large doubles

### ISSUE THREAD

**Issue by andreyv** [MikeMirzayanov/testlib#52]
Steps to reproduce:

* Compile `checkers/dcmp`
* Create empty `in` file
* Create  `ans` and `out` files with the content
```
-108029624244796670000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.000000000000
```
* Run `./dcmp in out ans`

Actual output:

    FAIL Expected double, but "-10802962424479667000000000000...000000000000000000.000000000000" found (ans)

**Comment by andreyv** [comment]
Just a guess, this line might be at fault: https://github.com/MikeMirzayanov/testlib/blob/master/testlib.h#L339

**Comment by MikeMirzayanov** [comment]
Fixed.
