### ISSUE TITLE
Allow validators to accept file from the command line

### ISSUE THREAD

**Issue by klenin** [MikeMirzayanov/testlib#58]
Essentially, either this:
```
void registerValidation(const chat *file_name)
{
    __testlib_ensuresPreconditions();
    testlibMode = _validator;
    // Note that  __testlib_set_binary() is already called by reset inside init.
    inf.init(file_name, _input); 
    inf.strict = true;
}
```
or modify `argc`/`argv` version of `registerValidation` to accept `--inputFile` parameter.

I can easily provide PR if you indicate which way you prefer.

**Comment by MikeMirzayanov** [comment]
I don't see a motivation to support it. This will result in heterogeneous incompatible validators.
