### ISSUE TITLE
Building issue (ms compiler)

### ISSUE THREAD

**Issue by RomanSteinberg** [MikeMirzayanov/testlib#59]
I've tried to build checker for doubles using Visual C++ 19.0 (MS VS 2015) and it fails to compile:
```
_file: не является членом "_iobuf"	check	testlib.h	431	
```
The piece of code which generates this error is
```
#ifndef __BORLANDC__
	_setmode(_fileno(file), O_BINARY);
#else
	setmode(fileno(file), O_BINARY);
#endif
```
I think if `testlib.h` is supposed to be compiled using borland compiler, it can allow to use ms compiler also.

**Comment by MikeMirzayanov** [comment]
Please, re-open it if it fails to be compiled now.
