### ISSUE TITLE
_setmode was not declared

### ISSUE THREAD

**Issue by ivankrut856** [MikeMirzayanov/testlib#61]
CYGWIN_NT-10.0 2.8.2(0.313/5/3) x86_64 Cygwin
g++ (GCC) 5.4.0
testlib.h 0.9.12
---
g++ gen.cpp -O2 -o -std=c++11 (or -std=gnu++11) gen.exe
In file included from gen.cpp:2:0: 
../testlib.h: In function ‘void __testlib_set_binary(FILE*)’: 
../testlib.h:431:41: error: ‘_setmode’ was not declared in this scope 
_setmode(_fileno(file), O_BINARY);
Help plz

**Comment by MikeMirzayanov** [comment]
Fixed now
