### ISSUE TITLE
force register* before actually using input and output streams

### ISSUE THREAD

**Issue by GassaFM** [MikeMirzayanov/testlib#62]
If one forgets registerTestlibCmd or the like, the input and output streams are in some unspecified state.
It would save developer time to have a clear error when such stream is used before registering.

**Comment by GassaFM** [comment]
One way to do it is to use macros for register* commands which change streams' internal state.
Another approach is to initialize the streams with something bad which, when used, manifests clearly and immediately.

**Comment by stgatilov** [comment]
And if one forgets to register generator, then random seed seems to **not** be set from cmd arguments. As a result, stress-testing with such generator may be a waste of time.

**Comment by MikeMirzayanov** [comment]
Fixed ages ago
