### ISSUE TITLE
ncmp.cpp компилируется с предупреждением

### ISSUE THREAD

**Issue by burunduk3** [MikeMirzayanov/testlib#67]
```
$ g++ -m32 -Wall -o ncmp -x c++ ncmp.cpp 
ncmp.cpp: In function ‘int main(int, char**)’:
ncmp.cpp:8:88: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘unsigned int’ [-Wformat=]
     setName("compare ordered sequences of signed int%ld numbers", 8 * sizeof(long long));
                                                                                        ^
```

Не воспроизводится при компилировании в 64-битную архитектуру.

Казалось бы, действительно, `size_t` следует выводить как `%zd` или `%zu` (https://www.gnu.org/software/libc/manual/html_node/Integer-Conversions.html), это избавляет от архитектурозависимости (на 32-битных системах подходит `%u`, на 64-битных — `%lu`).

**Comment by MikeMirzayanov** [comment]
Исправил на %d и каст к int. С %zu есть проблемы в старых VS.
