### ISSUE TITLE
How to match whitespaces using inf.readString()?

### ISSUE THREAD

**Issue by haleyk10198** [MikeMirzayanov/testlib#70]
I just realized that the "testlib.h" implements whitespace ' ' as a control character in the pattern class, and '\s' appears to be not recognized by the library too. I wonder if "testlib.h" has a built-in way to work around this issue, or should I change the separator used in my problem?

**Comment by alex65536** [comment]
Maybe try `'\ '`?

**Comment by MikeMirzayanov** [comment]
`'\ '` works.
